// <auto-generated />
namespace Carepoint.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateMessesConnectionwIsConnectionActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateMessesConnectionwIsConnectionActive));
        
        string IMigrationMetadata.Id
        {
            get { return "201904161821201_updateMessesConnection-w-IsConnectionActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
