// <auto-generated />
namespace Carepoint.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add2PropertiesToPasbaApps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add2PropertiesToPasbaApps));
        
        string IMigrationMetadata.Id
        {
            get { return "201902271503414_Add2PropertiesToPasbaApps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
